name = "FunOverF1"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["FunOverF1"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false # no "assume a typo is a new variable"
relaxedAutoImplicit = false # no "assume a typo is a new variable"
maxSynthPendingDepth = 3 # same as mathlib, changes behaviour of typeclass inference
# Enable all mathlib linters: automatically matches what mathlib uses.
weak.linter.mathlibStandardSet = true
weak.linter.flexible = true
weak.linter.style.header = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "FunOverF1"
